### ISSUE TITLE
Chat room / mailing list?

### ISSUE THREAD

**Issue by jhannah** [nigelhorne/ged2site#108]
Hi! Wow! Exciting! Installing this project now to give it a shot on my GEDCOM. :)

Is there a Slack/Discord/IRC/other people use for quick / informal discussions / questions about this project? Or an email mailing list? (I personally hate email, ignore it for months, but it's popular.) Whatever you prefer is totally fine, maybe you prefer GitHub Issues? It would be nice to have a community somewhere with 2024 discussions of genealogy in Perl, in case others are searching.

Thank you for reaching out on GitHub! I was searching (Mastodon, Slack, Discord, dead email lists) for anyone anywhere doing web genealogy in Perl nowadays, and hadn't found anyone until you posted your question in another GitHub repo.

**Comment by nigelhorne** [comment]
I did see a Facebook group and a mailing list somewhere, but they seem inactive.  Just pop in an issue here and I'll respond, usually within a day or two.

**Comment by nigelhorne** [comment]
You can look at https://www.miskatonic.org/pg/ but don't expect that mailing list to be very active.

**Comment by nigelhorne** [comment]
This is the Facebook group I found.  https://www.facebook.com/groups/316059398486703 - it talks about anything to do with technology in Genealogy.

**Comment by jhannah** [comment]
> You can look at https://www.miskatonic.org/pg/ but don't expect that mailing list to be very active.

I think that mailing list is dead? I tried to subscribe:

```
<perl-gedcom-subscribe@perl.org>: host perl.mx.develooper.com[147.75.38.233]
    said: 554 5.7.1 <perl-gedcom-subscribe@perl.org>: Recipient address
    rejected: Access denied (in reply to RCPT TO command)
```

And this says it's dead?: https://lists.perl.org/list/perl-gedcom.html

**Comment by nigelhorne** [comment]
That's a shame, thanks for the heads up.
