### ISSUE TITLE
Marpa::R2 on macOS

### ISSUE THREAD

**Issue by jhannah** [nigelhorne/ged2site#109]
FYI, v12 seems to install fine(?) on my old macOS (Ventura 13.6.7):

```
$ cpanm -v Marpa::R2
Successfully installed Marpa-R2-12.000000 (upgraded from 8.000000)
$ uname -a
Darwin Jays-2017-MacBook-Pro.local 22.6.0 Darwin Kernel Version 22.6.0: Mon Apr 22 20:54:28 PDT 2024; root:xnu-8796.141.3.705.2~1/RELEASE_X86_64 x86_64
$ perl -E 'say $^O'
darwin
```

So maybe you don't need this `darwin` code anymore?

	# I can't get Marpa::R2 versions 10 and 12 to build on OS/X or Solaris.
	# It's used by Genealogy::Gedcom::Date, so force version 8
	eval 'use Marpa::R2';
	if($@) {
		if(($^O eq 'solaris') || ($^O eq 'darwin')) {
			push @needfull, 'JKEGL/Marpa-R2-8.000000.tar.gz'
		} else {
			push @needfull, 'Marpa::R2';
		}
	}

No idea if it fails on current macOS, I don't have a machine that can run current macOS (Sonoma 14.*).

**Comment by nigelhorne** [comment]
Good point, mine runs as well.  So yes, I'll remove it from here and the [gedcom](https://github.com/nigelhorne/gedcom) application.

```
cpan[1]> install Marpa::R2                                                      
Fetching with LWP:
https://cpan.org/authors/01mailrc.txt.gz
Fetching with LWP:
https://cpan.org/modules/02packages.details.txt.gz
Fetching with LWP:
https://cpan.org/modules/03modlist.data.gz
Database was generated on Mon, 03 Jun 2024 00:10:39 GMT
Updating database file ... Done!
Marpa::R2 is up to date (12.000000).
```
