### ISSUE TITLE
FAM/MARR/DATE AFT explodes?

### ISSUE THREAD

**Issue by jhannah** [nigelhorne/ged2site#111]
```
✗ ./ged2site -cFdh 'Jay Weston Hannah' -l ~/Desktop/jay_new.ged
...
aft 1873 is invalid, need an exact date to create a DateTime at ./ged2site line 12599.
	4290 of ./ged2site
	1084 of ./ged2site
Date parse failure: left = (aft 1873) at ./ged2site line 12606, <GEN0> line 25430.
- program exits -
```

Here's my data that explodes:

```
✗ grep -B4 -i 'aft 1873' ~/Desktop/jay_new.ged
0 @F1445@ FAM
1 HUSB @I3971@
1 WIFE @I3973@
1 MARR
2 DATE AFT 1873
```

At a glance, looks like `ged2site` line 12,563 handles BEF but not AFT? Not sure what date it's trying to `datecmp()` against... Let me know if you want me to dive into debugging / possible PR.

**Comment by nigelhorne** [comment]
I have no sample data to check this against, so please try the patch I just committed and let me know if it has helped.
