### ISSUE TITLE
Render Family Tree even if spouse is UNKNOWN

### ISSUE THREAD

**Issue by jhannah** [nigelhorne/ged2site#116]
Wow, this static HTML is super cool! Kudos! 😄

But clicking through generations "breaks" when spouse is UNKNOWN? Clicking up up up through generations via the Family Tree... 🎉 But when I get to my "14 times great-grandfather" (`static-site/Alexander-Hannay-1470-1532.html`) there is no Family Tree, and the list of Children disappears... so there's nowhere to click to get to his children... I click on his father's name in text at the top and I'm back in business -- Family Tree is there again... but that gap is jarring going up, and impossible to go down?

If Family Tree was rendered even if only a single parent and/or child are known navigation would be a lot easier (up) and still possible (down)?

    ./ged2site -cFdh 'Jay Weston Hannah' -l ~/Desktop/jay_new.ged

**Comment by nigelhorne** [comment]
Since the biography also doesn't list the children, something is more fundamentally confused than not printing the family tree.  I'm having difficulty reproducing and diagnosing this, please run with the -w option enabled and see if that shows any clues.

**Comment by jhannah** [comment]
This is working now. Woot! My fork branch `112-and-115` 98af16deccef62925d85c9221c4b61a7f2eef971 output `static-site/I4172.html`.
