### ISSUE TITLE
Small biography bugs ("typos")

### ISSUE THREAD

**Issue by jhannah** [nigelhorne/ged2site#119]
No big deal, but I noticed a couple of typo-caliber bugs in my mother's biography `static-site/Sharon-Erlene-Humphrey-1947.html`:

> The child of *Earl Humphrey* and *Macil Stark*, **Sharon** is the mother of *Jay Hannah*, was born in Corpus Christi, Texas. She and married *James Hannah* (with whom she has had 2 surviving children*Jay Weston* and *Bradley Earl*) in Ft. Madison, IA on Jun 8, 1969.

* "She and married"?
* there's a space missing after "2 surviving children"

I started debugging / patching but quickly came to the thought that fixing my mom might break tons of other examples? Lots of potential subtle bugs? Does the project need a test suite so we could throw small GEDCOMs into a `t/` directory and write tests against these chunks of logic? (I see `tests/` but it's ~empty?)

**Comment by nigelhorne** [comment]
I do have plenty of gedcoms, however, I haven't automated their testing yet.  So, help in creating a test suite would be great.

**Comment by jhannah** [comment]
Typos confirmed fixed in `master` 1ea102256c3a10fec9497bbe3064e13094aa8a57 thanks!
