### ISSUE TITLE
static-site: HTML tidy?

### ISSUE THREAD

**Issue by jhannah** [nigelhorne/ged2site#122]
Thoughts on running the HTML files through whatever tidy converter so I can `git diff` my generated files cleanly? [A discussion thread](https://octodon.social/@deafferret/112615243349676194). I might run my own branch for that feature if you don't want it upstream. 🙂

**Comment by nigelhorne** [comment]
I use "weblint" to verify the HTML output.

**Comment by jhannah** [comment]
Note for future macOS users: `/usr/local/bin/tidy` is pre-installed apparently, this works great:

    find . -name '*.html' -exec tidy -quiet -im -wrap 0 -f errors.txt {} \;
