### ISSUE TITLE
Census Index link sometimes ".html"

### ISSUE THREAD

**Issue by cablespaghetti** [nigelhorne/ged2site#44]
I've noticed that the Census Index link sometimes point to ".html".

For example on https://genealogy.nigelhorne.com/cgi-bin/page.fcgi?page=people&home=1 currently points to `https://genealogy.nigelhorne.com/save_to/web/English/page.fcgi/.html`

This seems to be for cached pages in the save_to folder. If I do a Ctrl-Shift-R to invalidate the page cache, that seems to temporarily resolve the problem. 

As a slight tangent, I've tried messing around with all kinds of different caching settings, as I basically want to disable the "save_to" folder and use a reverse proxy cache instead but haven't had much luck. Could you explain the cache, disc_cache and memory cache options?

Thanks again!
Sam

**Comment by cablespaghetti** [comment]
Commenting out this seems to disable the save_to folder and so far looks to have solved/bodged around my issue.

```
        if(!$info->is_search_engine()) {
                $fb->init(save_to => {
                        directory => File::Spec->catfile($config->rootdir(), 'save_to'),
                        ttl => 3600 * 24,
                        create_table => 1
                });
        }
```

**Comment by nigelhorne** [comment]
Sam:

Thanks for your e-mail.  I suspect a cache is confused.  When you upload 
a new copy of your site please remove all of the 'save_to' directory and 
also the cache that disc_cache points to.  I need to make that clear in 
the documentation.  I'm hoping that will fix it.

I'll document disc_cache and memory_cache and pass it on to you - it's a 
good point that it's not clearly documented.

-Nigel

**Comment by nigelhorne** [comment]
Sam:

You need to do more than that - you also need to clear out whatever 
"disc_cache" points to - I'll put that in the documentation - which is 
rather sparse on that issue.

-Nigel

**Comment by cablespaghetti** [comment]
Thanks again Nigel!

**Comment by nigelhorne** [comment]
Documentation added.

Does removing the save_to directory on uploading a new website help?  Thinking about it, I used to have the same problem and realised that my cache was out of sync with the site - I'm hoping this will fix this problem as well.

**Comment by nigelhorne** [comment]
I believe that the latest 2 commits should fix this problem.
